spring.application.name=job-portal

# ===============================
# DATABASE CONFIG (NEON)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-jolly-sun-ancf6r3q-pooler.c-6.us-east-1.aws.neon.tech:5432/job-dekho?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tUa1jAcE8BIZ
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# ===============================
# EMAIL CONFIG (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ninjacoder135@gmail.com
spring.mail.password=gsslmgawgccpsdii

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
